[package]
name = "containr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
env_logger = { version = "0.11.6", features = ["unstable-kv"] }
log = { version = "0.4.22", features = ["kv"] }
